#pragma once

namespace AST {
enum class NodeType {
	Program = 0,
	RawText,
	Statement,
	ShellCommandSequence,
	Pipeline,
	SimpleCommandSequence,
	SimplePipeline,
	SimpleCommand,
	Rvalue,
	ValueAssignment,
	ProcessSubstitution,
	Block,
	IncludeStatement,
	ObjectInstantiation,
	PointerDeclaration,
	NewStatement,
	DeleteStatement,
	ClassDefinition,
	DatamemberDeclaration,
	MethodDefinition,
	ConstructorDefinition,
	DestructorDefinition,
	DoublequotedString,
	ObjectReference,
	ObjectReferenceLvalue,
	SelfReference,
	SelfReferenceLvalue,
	DynamicCast,
	DynamicCastTarget,
	BashVariable,
	ArrayIndex,
	ParameterExpansion,
	NamedFD,
	HeredocBody,
	HereString,
	ObjectAssignment,
	PrimitiveAssignment,
	ObjectAddress,
	PointerDereferenceRvalue,
	PointerDereferenceLvalue,
	TypeofExpression,
	Supershell,
	SubshellSubstitution,
	RawSubshell,
	BashCaseStatement,
	BashCaseInput,
	BashCasePattern,
	BashCasePatternHeader,
	BashCasePatternAction,
	BashSelectStatement,
	BashForStatement,
	BashInCondition,
	BashIfStatement,
	BashWhileStatement,
	BashUntilStatement,
	BashArithmeticForStatement,
	ERROR_TYPE
};
} // namespace AST
