#pragma once

namespace AST {
enum class NodeType {
	Program = 0,
	Statement,
	ShellCommandSequence,
	Pipeline,
	SimpleCommandSequence,
	SimplePipeline,
	SimpleCommand,
	Block,
	IncludeStatement,
	ObjectInstantiation,
	PointerDeclaration,
	NewStatement,
	DeleteStatement,
	ClassDefinition,
	DatamemberDeclaration,
	MethodDefinition,
	ConstructorDefinition,
	DestructorDefinition,
	DoublequotedString,
	ObjectReference,
	ObjectReferenceLvalue,
	SelfReference,
	SelfReferenceLvalue,
	DynamicCast,
	ObjectAssignment,
	PrimitiveAssignment,
	ObjectAddress,
	PointerDereferenceRvalue,
	PointerDereferenceLvalue,
	TypeofExpression,
	Supershell,
	SubshellSubstitution,
	RawSubshell,
	BashCaseStatement,
	BashSelectStatement,
	BashForStatement,
	BashIfStatement,
	BashWhileStatement,
	BashUntilStatement,
	BashArithmeticForStatement,
	ERROR_TYPE
};
} // namespace AST
