/**
 * Copyright (C) 2025 Andrew S. Rightenburg
 * Bash++: Bash with classes
 */

#pragma once

#include "ArrayIndex.h"
#include "BashArithmeticForCondition.h"
#include "BashArithmeticForStatement.h"
#include "BashArithmeticStatement.h"
#include "BashCaseInput.h"
#include "BashCasePatternAction.h"
#include "BashCasePattern.h"
#include "BashCasePatternHeader.h"
#include "BashCaseStatement.h"
#include "BashCommand.h"
#include "BashCommandSequence.h"
#include "BashForStatement.h"
#include "BashIfCondition.h"
#include "BashIfElseBranch.h"
#include "BashIfRootBranch.h"
#include "BashIfStatement.h"
#include "BashInCondition.h"
#include "BashPipeline.h"
#include "BashRedirection.h"
#include "BashSelectStatement.h"
#include "BashUntilStatement.h"
#include "BashVariable.h"
#include "BashWhileOrUntilCondition.h"
#include "BashWhileStatement.h"
#include "Block.h"
#include "ClassDefinition.h"
#include "ConstructorDefinition.h"
#include "DatamemberDeclaration.h"
#include "DeleteStatement.h"
#include "DestructorDefinition.h"
#include "DoublequotedString.h"
#include "DynamicCast.h"
#include "DynamicCastTarget.h"
#include "HeredocBody.h"
#include "HereString.h"
#include "IncludeStatement.h"
#include "MethodDefinition.h"
#include "NewStatement.h"
#include "ObjectAssignment.h"
#include "ObjectInstantiation.h"
#include "ObjectReference.h"
#include "ParameterExpansion.h"
#include "PointerDeclaration.h"
#include "PrimitiveAssignment.h"
#include "ProcessSubstitution.h"
#include "Program.h"
#include "RawSubshell.h"
#include "RawText.h"
#include "Rvalue.h"
#include "StringType.h"
#include "SubshellSubstitution.h"
#include "Supershell.h"
#include "TypeofExpression.h"
#include "ValueAssignment.h"
